server:
  port: ${PORT:8080}
spring:
  datasource:
    url: postgresql://sb_finance_tracker_prd:J0BRtLrGElMQ0hQsjU6bjimF1yr6g8l2@dpg-dae4tfvqj5pc73a9cnog-a.oregon-postgres.render.com/finance_tracker_93pt
    username: sb_finance_tracker_prd
    password: J0BRtLrGElMQ0hQsjU6bjimF1yr6g8l2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
