server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledgerly}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
